/**
 * DEV SEED EMITTER — ODD FANTASY-TEAM COUNT (carried-forward item C2).
 *
 * Serialises the scenario defined in `oddSeasonScenario.ts` (five teams, so one
 * team byes every round) into a seed PAIR the operator can paste:
 *
 *   supabase/seed/dev/seed_odd_raw.sql      — raw truth, one transaction, so the
 *       deferred triggers (mandatory captain, G15 composition, trade limits,
 *       round lock) validate the COMPLETE set at COMMIT. No bypass.
 *   supabase/seed/dev/seed_odd_derived.sql  — recomputeSeason output, serialized
 *       (prime invariant D15/G3: derived state is never hand-written).
 *
 * IT ADDS FILES, IT CHANGES NONE. `supabase/seed/seed_raw.sql` and
 * `seed_derived.sql` are untouched — a concurrent session may be editing seed
 * data, and this season carries its own id so the two can coexist in one database.
 *
 * Run: `npm run seed:generate:odd`. No DB connection or secrets required.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import type { RawSeason, DerivedState } from "../src/recompute/types.js";
import { buildOddSeason, SEASON } from "./oddSeasonScenario.js";

// ── SQL serialization (same conventions as the demo generator) ───────────────
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const val = (v: string | number | boolean | null): string =>
  v === null
    ? "NULL"
    : typeof v === "string"
      ? q(v)
      : typeof v === "boolean"
        ? v
          ? "true"
          : "false"
        : String(v);
const row = (vals: (string | number | boolean | null)[]) =>
  `(${vals.map(val).join(", ")})`;

function insert(
  table: string,
  cols: string[],
  rows: (string | number | boolean | null)[][],
): string {
  if (rows.length === 0) return `-- (no rows for ${table})\n`;
  return (
    `INSERT INTO ${table} (${cols.join(", ")}) VALUES\n` + rows.map(row).join(",\n") + ";\n"
  );
}

function emitRaw(raw: RawSeason): string {
  const out: string[] = [];
  out.push(`-- NSCC Fantasy — DEV SEED: ODD FANTASY-TEAM COUNT (5 teams).`);
  out.push(`-- Generated by scripts/generate-seed-odd.ts — do not hand-edit.`);
  out.push(`-- PURPOSE: carried-forward item C2 — render the BYE. Five teams means one`);
  out.push(`-- team byes every round, scored against that round's median (D18/G9).`);
  out.push(`-- Fielders in dismissal strings are CANONICAL PLAYER IDS (D25) so the full`);
  out.push(`-- path actually carries fielding credit.`);
  out.push(`-- Replace __OWNER_A..E__ with real auth.users ids before running.`);
  out.push(`-- Idempotent, and scoped to its OWN season id: it never touches the demo season.`);
  out.push(`-- ONE transaction, so the deferred triggers validate the COMPLETE set at COMMIT.`);

  const S = q(SEASON);
  const R_OF = `(SELECT id FROM rounds WHERE season_id = ${S})`;
  const M_OF = `(SELECT id FROM matches WHERE round_id IN ${R_OF})`;
  const T_OF = `(SELECT id FROM fantasy_teams WHERE season_id = ${S})`;
  const P_OF = `(SELECT id FROM players WHERE season_id = ${S})`;
  const SC_OF = `(SELECT id FROM scorecards WHERE match_id IN ${M_OF})`;
  const wipe = [
    `DELETE FROM player_match_scores WHERE match_id IN ${M_OF};`,
    `DELETE FROM price_history WHERE player_id IN ${P_OF};`,
    `DELETE FROM team_cap_snapshots WHERE fantasy_team_id IN ${T_OF};`,
    `DELETE FROM team_round_scores WHERE fantasy_team_id IN ${T_OF};`,
    `DELETE FROM h2h_results WHERE round_id IN ${R_OF};`,
    `DELETE FROM ladder WHERE season_id = ${S};`,
    `DELETE FROM overall_leaderboard WHERE season_id = ${S};`,
    `DELETE FROM trades WHERE fantasy_team_id IN ${T_OF};`,
    `DELETE FROM selections WHERE fantasy_team_id IN ${T_OF};`,
    `DELETE FROM dismissals WHERE scorecard_id IN ${SC_OF};`,
    `DELETE FROM batting_lines WHERE scorecard_id IN ${SC_OF};`,
    `DELETE FROM bowling_lines WHERE scorecard_id IN ${SC_OF};`,
    `DELETE FROM scorecard_lineup WHERE scorecard_id IN ${SC_OF};`,
    `DELETE FROM scorecards WHERE match_id IN ${M_OF};`,
    `DELETE FROM matches WHERE round_id IN ${R_OF};`,
    `DELETE FROM fantasy_teams WHERE season_id = ${S};`,
    `DELETE FROM rounds WHERE season_id = ${S};`,
    `DELETE FROM players WHERE season_id = ${S};`,
    `DELETE FROM seasons WHERE id = ${S};`,
  ];
  out.push(`BEGIN;`);
  out.push(`-- Idempotent wipe of the dev season (children first).`);
  out.push(wipe.join("\n"));
  out.push("");
  out.push(
    `INSERT INTO seasons (id, name, config) VALUES\n(${val(SEASON)}, ${val(
      "NSCC Fantasy — Dev Season (odd team count, bye)",
    )}, ${q(JSON.stringify(raw.config))}::jsonb);\n`,
  );
  out.push(
    insert(
      "players",
      ["id", "season_id", "registry_key", "display_name", "role", "wk_eligible", "starting_price", "active"],
      raw.players.map((p) => [
        p.id, SEASON, p.registryKey, p.displayName, p.role, p.wkEligible, p.startingPrice, p.active,
      ]),
    ),
  );
  out.push(
    insert(
      "rounds",
      ["id", "season_id", "seq", "name", "lock_at"],
      raw.rounds.map((r) => [r.id, SEASON, r.seq, r.name, r.lockAt]),
    ),
  );
  out.push(
    insert(
      "matches",
      ["id", "round_id", "grade", "opponent", "status", "final_day_date", "finalised_at"],
      raw.matches.map((m) => [
        m.id, m.roundId, m.grade, m.opponent, m.status, m.finalDayDate, m.finalisedAt,
      ]),
    ),
  );
  out.push(
    insert(
      "scorecards",
      ["id", "match_id", "wicket_keeper_player_id", "review_state"],
      raw.scorecards.map((sc) => [sc.id, sc.matchId, sc.wicketKeeperPlayerId, sc.reviewState]),
    ),
  );
  out.push(
    insert(
      "scorecard_lineup",
      ["scorecard_id", "player_id"],
      raw.scorecards.flatMap((sc) => sc.lineup.map((p) => [sc.id, p])),
    ),
  );
  out.push(
    insert(
      "batting_lines",
      ["scorecard_id", "player_id", "runs", "balls_faced", "fours", "sixes"],
      raw.scorecards.flatMap((sc) =>
        sc.batting.map((b) => [sc.id, b.playerId, b.runs, b.ballsFaced, b.fours, b.sixes]),
      ),
    ),
  );
  out.push(
    insert(
      "bowling_lines",
      ["scorecard_id", "player_id", "overs", "runs_conceded", "wickets"],
      raw.scorecards.flatMap((sc) =>
        sc.bowling.map((b) => [sc.id, b.playerId, b.overs, b.runsConceded, b.wickets]),
      ),
    ),
  );
  out.push(
    insert(
      "dismissals",
      // `resolved_text` per 0006 (the column formerly called `raw_text`), matching
      // the demo generator. The dev seed has no separate operator source string,
      // so `source_text` is left NULL rather than duplicating the canonical form.
      ["scorecard_id", "seq", "resolved_text"],
      raw.scorecards.flatMap((sc) => sc.dismissals.map((d, i) => [sc.id, i, d])),
    ),
  );
  out.push(
    insert(
      "fantasy_teams",
      ["id", "season_id", "owner_profile_id", "name"],
      raw.fantasyTeams.map((t) => [t.id, SEASON, t.ownerProfileId, t.name]),
    ),
  );
  out.push(
    insert(
      "selections",
      ["id", "fantasy_team_id", "round_id", "player_id", "is_captain", "is_vice_captain"],
      raw.selections.map((s) => [
        s.id, s.fantasyTeamId, s.roundId, s.playerId, s.isCaptain, s.isViceCaptain,
      ]),
    ),
  );
  out.push(
    insert(
      "trades",
      ["id", "fantasy_team_id", "kind", "player_id", "price", "round_id", "created_at"],
      raw.trades.map((t) => [
        t.id, t.fantasyTeamId, t.kind, t.playerId, t.price, t.roundId, t.createdAt,
      ]),
    ),
  );
  out.push(`COMMIT;`);
  return out.join("\n") + "\n";
}

function emitDerived(d: DerivedState): string {
  const out: string[] = [];
  out.push(`-- NSCC Fantasy — DEV SEED (odd team count): DERIVED STATE.`);
  out.push(`-- recomputeSeason output (D15/G3) — engine-computed, never hand-written.`);
  out.push(`-- Paste AFTER seed_odd_raw.sql. Idempotent.`);
  out.push(`BEGIN;`);
  const S = q(SEASON);
  out.push(
    `DELETE FROM player_match_scores WHERE match_id IN (SELECT id FROM matches WHERE round_id IN (SELECT id FROM rounds WHERE season_id = ${S}));`,
  );
  out.push(
    `DELETE FROM price_history WHERE player_id IN (SELECT id FROM players WHERE season_id = ${S});`,
  );
  out.push(
    `DELETE FROM team_cap_snapshots WHERE fantasy_team_id IN (SELECT id FROM fantasy_teams WHERE season_id = ${S});`,
  );
  out.push(
    `DELETE FROM team_round_scores WHERE fantasy_team_id IN (SELECT id FROM fantasy_teams WHERE season_id = ${S});`,
  );
  out.push(
    `DELETE FROM h2h_results WHERE round_id IN (SELECT id FROM rounds WHERE season_id = ${S});`,
  );
  out.push(`DELETE FROM ladder WHERE season_id = ${S};`);
  out.push(`DELETE FROM overall_leaderboard WHERE season_id = ${S};`);
  out.push("");
  out.push(
    insert(
      "player_match_scores",
      ["match_id", "player_id", "played", "batting", "bowling", "fielding", "bonuses", "base"],
      d.playerMatchScores.map((s) => [
        s.matchId, s.playerId, s.played, s.batting, s.bowling, s.fielding, s.bonuses, s.base,
      ]),
    ),
  );
  out.push(
    insert(
      "price_history",
      ["player_id", "match_id", "seq", "price"],
      d.priceHistory.map((p) => [p.playerId, p.matchId, p.seq, p.price]),
    ),
  );
  out.push(
    insert(
      "team_cap_snapshots",
      ["fantasy_team_id", "as_of_round_id", "cap_remaining", "invested_value", "team_value"],
      d.teamCapSnapshots.map((c) => [
        c.fantasyTeamId, c.asOfRoundId, c.capRemaining, c.investedValue, c.teamValue,
      ]),
    ),
  );
  out.push(
    insert(
      "team_round_scores",
      ["fantasy_team_id", "round_id", "total", "captain_player_id"],
      d.teamRoundScores.map((t) => [t.fantasyTeamId, t.roundId, t.total, t.captainPlayerId]),
    ),
  );
  out.push(
    insert(
      "h2h_results",
      ["round_id", "home_team_id", "away_team_id", "home_points", "away_points", "bye_median", "outcome"],
      d.h2hResults.map((h) => [
        h.roundId, h.homeTeamId, h.awayTeamId, h.homePoints, h.awayPoints, h.byeMedian, h.outcome,
      ]),
    ),
  );
  out.push(
    insert(
      "ladder",
      ["season_id", "fantasy_team_id", "played", "wins", "losses", "ties", "points_for", "ladder_points"],
      d.ladder.map((l) => [
        SEASON, l.fantasyTeamId, l.played, l.wins, l.losses, l.ties, l.pointsFor, l.ladderPoints,
      ]),
    ),
  );
  out.push(
    insert(
      "overall_leaderboard",
      ["season_id", "fantasy_team_id", "total_points"],
      d.overallLeaderboard.map((o) => [SEASON, o.fantasyTeamId, o.totalPoints]),
    ),
  );
  out.push(`COMMIT;`);
  return out.join("\n") + "\n";
}

// ── Run ─────────────────────────────────────────────────────────────────────
const { raw, derived, tradePrices } = buildOddSeason();

const here = dirname(fileURLToPath(import.meta.url));
const seedDir = resolve(here, "../supabase/seed/dev");
mkdirSync(seedDir, { recursive: true });
writeFileSync(resolve(seedDir, "seed_odd_raw.sql"), emitRaw(raw));
writeFileSync(resolve(seedDir, "seed_odd_derived.sql"), emitDerived(derived));

const byes = derived.h2hResults.filter((h) => h.awayTeamId === null);
console.log("Wrote supabase/seed/dev/seed_odd_raw.sql and seed_odd_derived.sql");
console.log(
  `  ${raw.players.length} players · ${raw.fantasyTeams.length} teams (ODD) · ` +
    `${raw.rounds.length} rounds · ${byes.length} bye fixture(s) · ` +
    `${derived.ladder.length} ladder rows`,
);
for (const b of byes) {
  console.log(`  bye: team ${b.homeTeamId} scored ${b.homePoints} v median ${b.byeMedian}`);
}
console.log(
  `  round-2 trade priced at entering-round values: sell ${tradePrices.sell}, buy ${tradePrices.buy}`,
);
